@api = http://localhost:3000/reportes

### get all reportes
GET {{api}}

### getTotalReportes

GET {{api}}/count


### delete all reportes

 DELETE {{api}}


### create reporte


POST {{api}}
Content-Type: application/json

{
    "idEmpleado": 1,
    "nombreProducto": "Reporte 777",
    "prioridad": 1,
    "Descripcion": "cuarto reporte",
    "latitude": "123.321.212",
    "longitude": "344.322.213",
    "aprobado": 1,
    "imagenTexto": "dinasdicnipsdn",
    "completado": 0

}


### update reporte by id

PUT {{api}}/3
Content-Type: application/json

{
    "idEmpleado": 1,
    "nombreProducto": "secadora",
    "prioridad": 1,
    "Descripcion": "primer reporte",
    "latitude": "123",
    "longitude": "321",
    "estatus": 1,
    "imagenTexto": "dinasdicnipsdn",
    "completado": 0
}





### get reporte by id

GET {{api}}/2

### delete reporte by id


 DELETE {{api}}/1



### reiniciar id reportes

POST {{api}}/reiniciarIdReportes


